env:
  current_network: "mainnet"
  token_contract: "0xc6bb661eda683bdc792b3e456a206a92cc3cb92e"
  proxy_contract: "0xb00c8237e286abcac07e6795ab74e1ec1b075870"
  zrc1_contract: "0x06f70655d4aa5819e711563eb2383655449f24e9"
  zrc6_contract: "0x8ab2af0cccee7195a7c16030fbdfde6501d91903"
  migrator_contract: "0xdaaf7e1479ef28ba7818b48ae5664b59b738dc97"
  rewards_contract: "0x4e932c4069d34d9b06c14b5f610de826302b1011"
  voucher_contract: "0xffe86530c8cf9e92751c6cbcd1ff8af12e778805" 
  ownership_contract: "0x35eea03bb8e9dc7e1f22c12c8a1007ea968e5bd8"

namespace: duck

image:
  app:
    pullSecret: aws-registry

ingress:
  host: duck.community

replicas: 1

# filebeat requirements
logPath: /app/logs
