image:
  app: 
    url: 465700395685.dkr.ecr.eu-west-1.amazonaws.com/duck/client
    tag: latest
    pullPolicy: IfNotPresent
    pullSecret: ~

port: 3000
targetPort: 3000

replicas: 1

resources:
  limits:
    cpu: 0.1
    memory: 128M
  requests:
    cpu: 0.1
    memory: 128M
